name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v simpleGoServer.go

    - name: Step 1 - Create a temporary artifact downloads folder
      run: mkdir downloads
      
    - name: step 2 - Add artifacts to publish to the temp folder
      run: |
        cd downloads
        cp ../simpleGoServer ./
        cd ..
  
    - name: Step 3 - Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with: 
        name: assets-for-download
        path: downloads